### ISSUE TITLE
Email contact

### ISSUE THREAD

**Issue by asim** [bottos-project/bottos#4]
Hey. I'm the creator of micro. I noticed you're using micro in your project. This is very exciting. Thanks for using it as part of a blockchain project. You are one of the first. I'd be interested to chat more about how you're finding it and if there's anything that could be improved. Please let me know if you've got a contact email address.

**Comment by luomeiqin** [comment]
Hi, asim:
I am glad to hear that we are the first blockchain project to use micro as a part. Bottos is designed to be a public blockchain for AI ecosystem. Our vision is to provide a much scalable, easy debugging and high concurrency blockchain. As you can see, Botto's blockchain architecture is designed to have three layers. Core Layer provides blockchain basic infrastructure. services layer provide multi-services so that Dapps in AI ecosystem can much easier to construct.  Micro provides simple cloud-native systems building and it's microservices architecture pattern attract us. Btw, thank you for creating such an awesome project.  I would like to share more about how we use micro, my email address: maypen890@aliyun.com

**Comment by asim** [comment]
Thanks May, following up in email.
